# Generated by Django 5.0.7 on 2026-07-15 08:36

import App_Core.model_utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Info',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('job', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('company', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('birthday', models.DateField(blank=True, default=None, null=True)),
                ('gender', models.CharField(blank=True, choices=[('', ''), ('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], default='', max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=App_Core.model_utils.user_directory_path_profile)),
                ('about', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profile',
                'ordering': ('-id',),
            },
        ),
    ]
