# Generated by 02-check-django-coolify.sh --scaffold (template: ecom_final, docs/03 3.3)
FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# curl: Coolify runs the healthcheck with curl/wget INSIDE the container; python:slim has neither.
# git: requirements.txt installs packages from git+https://
RUN apt-get update && apt-get install -y --no-install-recommends curl git \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# settings.py reads these at import time: fake values for collectstatic only, real ones come from Coolify.
RUN DOMAIN=build-only \
    EMAIL_HOST_PASSWORD=build-only \
    EMAIL_HOST_USER=build-only@example.com \
    EMAIL_PORT=587 \
    ENVIRONMENT=prod \
    POSTGRES_HOST=build-only \
    POSTGRES_PASSWORD=build-only \
    POSTGRES_PORT=5432 \
    POSTGRES_USER=build-only \
    SECRET_KEY=build-only-not-a-real-secret-key-padding-to-50-chars-min \
    VPS=build-only \
    python manage.py collectstatic --noinput

RUN chmod +x /app/entrypoint.sh

EXPOSE 8000
ENTRYPOINT ["/app/entrypoint.sh"]
