# Generated by Django 5.0.7 on 2026-07-15 08:36

import App_Core.model_utils
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('author', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('is_sale', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_at', models.DateTimeField(blank=True, default=App_Core.model_utils.get_default_datetime, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=App_Core.model_utils.user_directory_path_post)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=App_Core.model_utils.user_directory_path_post)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Post',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=App_Core.model_utils.user_directory_path_subject)),
            ],
            options={
                'verbose_name_plural': 'Subject',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='App_Post.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True)),
                ('previous_image_urls', models.TextField(blank=True, default='', editable=False)),
                ('post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Post.post')),
            ],
            options={
                'verbose_name_plural': 'PostContent',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PostPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to=App_Core.model_utils.user_directory_path_postphoto)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_post', to='App_Post.post')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='App_Post.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='App_Post.subject'),
        ),
        migrations.CreateModel(
            name='SubSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=App_Core.model_utils.user_directory_path_subsubject)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubjects', to='App_Post.subject')),
            ],
            options={
                'verbose_name_plural': 'SubSubject',
                'ordering': ('-id',),
                'unique_together': {('subject', 'title')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='subsubject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='App_Post.subsubject'),
        ),
    ]
