# Generated by Django 5.0.7 on 2026-07-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommerceBehaviorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_guest_cart', models.BooleanField(default=False, verbose_name='Cho phép thêm giỏ hàng khi chưa đăng nhập')),
                ('allow_guest_wishlist', models.BooleanField(default=False, verbose_name='Cho phép thêm yêu thích khi chưa đăng nhập')),
            ],
            options={
                'verbose_name': 'Cấu hình thương mại',
                'verbose_name_plural': 'Cấu hình thương mại',
            },
        ),
        migrations.CreateModel(
            name='QuanlyMenuConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_dashboard', models.BooleanField(default=True, verbose_name='Dashboard')),
                ('show_product', models.BooleanField(default=True, verbose_name='Sản Phẩm')),
                ('show_productvariant', models.BooleanField(default=True, verbose_name='Biến Thể')),
                ('show_category', models.BooleanField(default=True, verbose_name='Danh Mục')),
                ('show_order', models.BooleanField(default=True, verbose_name='Đơn Hàng')),
                ('show_customer', models.BooleanField(default=True, verbose_name='Khách Hàng')),
                ('show_review', models.BooleanField(default=True, verbose_name='Đánh giá')),
                ('show_post', models.BooleanField(default=True, verbose_name='Bài Viết')),
                ('show_subject', models.BooleanField(default=True, verbose_name='Chủ Đề')),
                ('show_comment', models.BooleanField(default=True, verbose_name='Bình Luận')),
                ('show_contact', models.BooleanField(default=True, verbose_name='Liên Hệ')),
                ('show_email', models.BooleanField(default=True, verbose_name='Email')),
                ('show_payment', models.BooleanField(default=True, verbose_name='Thanh Toán')),
                ('show_pageview', models.BooleanField(default=True, verbose_name='Truy Cập')),
                ('default_page', models.CharField(choices=[('dashboard', 'Dashboard'), ('product', 'Sản Phẩm'), ('productvariant', 'Biến Thể'), ('category', 'Danh Mục'), ('order', 'Đơn Hàng'), ('customer', 'Khách Hàng'), ('review', 'Đánh giá'), ('post', 'Bài Viết'), ('subject', 'Chủ Đề'), ('comment', 'Bình Luận'), ('contact', 'Liên Hệ'), ('email', 'Email'), ('payment', 'Thanh Toán'), ('pageview', 'Truy Cập')], default='dashboard', help_text='Trang sẽ mở khi truy cập /quanly/. Nếu ẩn menu Dashboard, hãy chọn trang khác.', max_length=20, verbose_name='Trang mặc định')),
            ],
            options={
                'verbose_name': 'Cấu hình menu quản lý',
                'verbose_name_plural': 'Cấu hình menu quản lý',
            },
        ),
    ]
