# Generated by Django 5.0.14 on 2026-07-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Quanly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommerceBehaviorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_guest_cart', models.BooleanField(default=False, verbose_name='Cho phép thêm giỏ hàng khi chưa đăng nhập')),
                ('allow_guest_wishlist', models.BooleanField(default=False, verbose_name='Cho phép thêm yêu thích khi chưa đăng nhập')),
            ],
            options={
                'verbose_name': 'Cấu hình thương mại',
                'verbose_name_plural': 'Cấu hình thương mại',
            },
        ),
    ]
